# Generated by Django 5.2.8 on 2026-02-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('occasion', models.CharField(choices=[('Valentine', 'Valentine'), ('New Year', 'New Year'), ('Easter', 'Easter'), ('Christmas', 'Christmas'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=20)),
                ('theme', models.CharField(choices=[('Romantic', 'Romantic'), ('Friendly', 'Friendly'), ('Family', 'Family'), ('Elegant', 'Elegant')], max_length=20)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
