# Generated by Django 5.2.8 on 2026-02-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
