# Generated by Django 4.2.28 on 2026-03-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valapp', '0002_linktype_userlink_anonymousmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='userlink',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
