# Generated by Django 4.2.28 on 2026-03-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valapp', '0003_remove_userlink_unique_id_userlink_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='occasion',
            field=models.CharField(choices=[('Valentine', 'Valentine'), ('New Year', 'New Year'), ('Easter', 'Easter'), ('Christmas', 'Christmas'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ("Eid'l fitr", "Eid'l fitr"), ("Eid'l mubarak", "Eid'l mubarak")], max_length=20),
        ),
    ]
