# Generated by Django 4.2.28 on 2026-03-29 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valapp', '0005_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='messages/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='valapp.message')),
            ],
        ),
    ]
